// <auto-generated />
using System;
using LojaPerfumes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaPerfumes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LojaPerfumesContext))]
    [Migration("20261008215125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("EstoqueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PerfumeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("EstoqueId");

                    b.HasIndex("PerfumeId")
                        .IsUnique();

                    b.ToTable("Estoques", (string)null);
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("ItemPedidoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PerfumeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ItemPedidoId");

                    b.HasIndex("PerfumeId");

                    b.HasIndex("PedidoId", "PerfumeId")
                        .IsUnique();

                    b.ToTable("ItensPedido", (string)null);
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Perfume", b =>
                {
                    b.Property<Guid>("PerfumeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PerfumeId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Perfumes", (string)null);
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("LojaPerfumes.Domain.Entities.Perfume", "Perfume")
                        .WithOne("Estoque")
                        .HasForeignKey("LojaPerfumes.Domain.Entities.Estoque", "PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("LojaPerfumes.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaPerfumes.Domain.Entities.Perfume", "Perfume")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("LojaPerfumes.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Perfume", b =>
                {
                    b.HasOne("LojaPerfumes.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Perfumes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Perfumes");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("LojaPerfumes.Domain.Entities.Perfume", b =>
                {
                    b.Navigation("Estoque");

                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
